# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='tag',
            field=models.CharField(default='baby', max_length=6),
        ),
    ]
