# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_img_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='baby', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.Tag'),
        ),
    ]
