# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_auto_20170725_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='img',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='img',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='img',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
