# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0004_auto_20170731_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
